/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target, mod));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScriptLauncher
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var fs = __toESM(require("fs"));
var ScriptLauncher = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.scripts = [];
    this.barElements = [];
    this.verifiedScripts = /* @__PURE__ */ new Set();
    this.runningScriptsToStop = /* @__PURE__ */ new Map();
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.createIcons();
      this.addSettingTab(new ScriptLauncherSettingTab(this.app, this));
      for (const script of this.scripts) {
        if (script.runOnStartup) {
          this.runScript(script);
        }
      }
      this.addCommand({
        id: "run-script",
        name: "Run script",
        editorCallback: (editor, view) => {
          new ScriptSelectionModal(this).open();
        }
      });
    });
  }
  onunload() {
    for (const [, childProcess] of this.runningScriptsToStop) {
      childProcess.kill();
    }
  }
  exists(path) {
    try {
      return fs.lstatSync(path).isFile();
    } catch (e) {
      return false;
    }
  }
  createIcons() {
    for (const el of this.barElements) {
      el.remove();
    }
    for (const script of this.scripts) {
      if (!script.showOnBottomBar)
        continue;
      if (!this.verifiedScripts.has(script.path) && !this.exists(script.path))
        continue;
      this.verifiedScripts.add(script.path);
      const statusBarItemEl = this.addStatusBarItem();
      if (script.icon) {
        (0, import_obsidian.setIcon)(statusBarItemEl, script.icon);
        if (statusBarItemEl.childElementCount === 0) {
          statusBarItemEl.setText(script.name);
        }
      } else {
        statusBarItemEl.setText(script.name);
      }
      statusBarItemEl.onClickEvent((_) => {
        this.runScript(script);
      });
      this.barElements.push(statusBarItemEl);
    }
  }
  loadSettings() {
    return __async(this, null, function* () {
      let scripts = yield this.loadData();
      if (!scripts)
        scripts = [];
      this.scripts = scripts;
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.scripts);
    });
  }
  runScript(script) {
    var _a, _b;
    const childProcess = (0, import_child_process.spawn)(script.path, [(_a = this.getVaultPath()) != null ? _a : "", (_b = this.getFilePath()) != null ? _b : ""], { shell: true });
    if (!childProcess.pid) {
      new import_obsidian.Notice(`Failed to start script: ${script.name}`);
      return;
    }
    const pid = childProcess.pid;
    childProcess.stdout.on("data", (data) => {
      console.log(`stdout: ${data}`);
      new import_obsidian.Notice(data);
    });
    childProcess.stderr.on("data", (data) => {
      console.log(`stderr: ${data}`);
      new import_obsidian.Notice(data);
    });
    childProcess.on("error", (error) => {
      new import_obsidian.Notice(`error: ${error}`);
    });
    if (script.showExitCode) {
      childProcess.on("close", (code) => {
        new import_obsidian.Notice(`child process exited with code ${code}`);
      });
    }
    this.runningScriptsToStop.set(pid, childProcess);
    childProcess.on("exit", (code) => {
      this.runningScriptsToStop.delete(pid);
    });
  }
  getVaultPath() {
    const adapter = app.vault.adapter;
    if (adapter instanceof import_obsidian.FileSystemAdapter) {
      return adapter.getBasePath();
    }
    return null;
  }
  getFilePath() {
    var _a;
    return (_a = app.workspace.getActiveFile()) == null ? void 0 : _a.path;
  }
};
var ScriptLauncherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    this.createSettings();
  }
  onSettingsChange() {
    return __async(this, null, function* () {
      this.plugin.createIcons();
      yield this.plugin.saveSettings();
    });
  }
  createSettings() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Script Launcher Settings" });
    for (let i = 0; i < this.plugin.scripts.length; i++) {
      const script = this.plugin.scripts[i];
      new import_obsidian.Setting(containerEl).setName("========= Script " + i + " =========");
      new import_obsidian.Setting(containerEl).setName("Script name").addText((text) => text.setPlaceholder("Unnamed").setValue(script.name).onChange((value) => __async(this, null, function* () {
        script.name = value;
        yield this.onSettingsChange();
      })));
      new import_obsidian.Setting(containerEl).setName("Script path").addText((text) => text.setPlaceholder("path to file").setValue(script.path).onChange((value) => __async(this, null, function* () {
        script.path = value;
        yield this.onSettingsChange();
      }))).addButton((button) => button.setButtonText("Browse").onClick(() => {
        const input = document.createElement("input");
        input.type = "file";
        input.style.display = "none";
        document.body.appendChild(input);
        input.onchange = (e) => __async(this, null, function* () {
          var _a;
          const file = (_a = e.target.files) == null ? void 0 : _a[0];
          if (file) {
            let filePath = file.path;
            if (!filePath) {
              try {
                filePath = require("electron").webUtils.getPathForFile(file);
              } catch (err) {
                console.error(err);
              }
            }
            if (filePath) {
              script.path = filePath;
              yield this.onSettingsChange();
              this.createSettings();
            } else {
              new import_obsidian.Notice(`Could not get absolute path for: ${file.name}`);
            }
          }
          document.body.removeChild(input);
        });
        input.click();
      }));
      new import_obsidian.Setting(containerEl).setName("Show on bottom bar").addToggle((toggle) => {
        var _a;
        toggle.setValue((_a = script.showOnBottomBar) != null ? _a : false).onChange((v) => __async(this, null, function* () {
          script.showOnBottomBar = v;
          yield this.onSettingsChange();
        }));
      });
      new import_obsidian.Setting(containerEl).setName("Run on startup").addToggle((toggle) => {
        var _a;
        toggle.setValue((_a = script.runOnStartup) != null ? _a : false).onChange((v) => __async(this, null, function* () {
          script.runOnStartup = v;
          yield this.onSettingsChange();
        }));
      });
      new import_obsidian.Setting(containerEl).setName("Show exit code").addToggle((toggle) => {
        var _a;
        toggle.setValue((_a = script.showExitCode) != null ? _a : false).onChange((v) => __async(this, null, function* () {
          script.showExitCode = v;
          yield this.onSettingsChange();
        }));
      });
      new import_obsidian.Setting(containerEl).setName("Icon").addText((text) => {
        var _a;
        return text.setPlaceholder("icon").setValue((_a = script.icon) != null ? _a : "").onChange((value) => __async(this, null, function* () {
          script.icon = value;
          yield this.onSettingsChange();
        }));
      });
      new import_obsidian.Setting(containerEl).setName("Delete").addButton((button) => {
        button.setIcon("trash").onClick((evt) => __async(this, null, function* () {
          this.plugin.scripts.remove(script);
          this.createSettings();
          yield this.onSettingsChange();
        }));
      });
    }
    new import_obsidian.Setting(containerEl).setName("Add Script").addButton((button) => button.setIcon("plus-with-circle").onClick((evt) => __async(this, null, function* () {
      this.plugin.scripts.push({
        name: "Unnamed",
        path: ""
      });
      yield this.plugin.saveSettings();
      this.createSettings();
    })));
  }
};
var ScriptSelectionModal = class extends import_obsidian.SuggestModal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
  }
  getSuggestions(query) {
    return this.plugin.scripts.filter((script) => script.name.toLowerCase().includes(query.toLowerCase()));
  }
  renderSuggestion(script, el) {
    el.createEl("div", { text: script.name });
  }
  onChooseSuggestion(script, evt) {
    this.plugin.runScript(script);
  }
};

/* nosourcemap */